export const title = ' | TODOLIST';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_LOADED_FAMILY = 'USER_LOADED_FAMILY';
export const ADD_NEW_FAMILY_MEMBERS = 'ADD_NEW_FAMILY_MEMBERS';

export const TASKS_FETCHED = 'TASKS_FETCHED';